"""create chat_history table

Revision ID: 3e587a19c201
Revises: 0d6f3cc2009a
Create Date: 2026-04-22 15:48:45.848720

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3e587a19c201"
down_revision: Union[str, Sequence[str], None] = "0d6f3cc2009a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 与上一版无模型差异，当时 autogenerate 生成为空；保留链顶 revision 以与历史一致。
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
